plugins {
    id 'java'
    id 'org.springframework.boot' version '4.0.6'
    id 'io.spring.dependency-management' version '1.1.7'
    id 'org.sonarqube' version "7.3.0.8198"
    id 'com.google.protobuf' version "0.10.0"
    id 'jacoco'
}

jacocoTestReport {
    executionData tasks.withType(Test)

    reports {
        xml.required = true
        html.required = true
    }
}

sonar {
    properties {
        property "sonar.projectName", "user-service"
        property "sonar.projectKey", "com.minispring:user-service"
        property "sonar.qualitygate.wait", true
    }
}

group = 'com.minispring'
version = '0.0.1-SNAPSHOT'
description = 'user-service'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

repositories {
    mavenCentral()
}

sourceSets {
    integrationTest {
        java.srcDir file('src/integrationTest/java')
        resources.srcDir file('src/integrationTest/resources')
        compileClasspath += sourceSets.main.output + sourceSets.test.output
        runtimeClasspath += sourceSets.main.output + sourceSets.test.output
    }
}

configurations.integrationTestImplementation.extendsFrom(configurations.testImplementation)
configurations.integrationTestRuntimeOnly.extendsFrom(configurations.testRuntimeOnly)

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-liquibase'
    implementation 'org.springframework.boot:spring-boot-starter-cache'
    implementation 'org.springframework.boot:spring-boot-starter-webmvc'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-oauth2-resource-server'
    implementation 'org.springframework.grpc:spring-grpc-spring-boot-starter:1.0.3'
    implementation 'com.google.protobuf:protobuf-java:4.35.0'
    implementation 'com.google.protobuf:protobuf-java-util:4.35.0'
    implementation 'net.lbruun.springboot:preliquibase-spring-boot-starter:2.0.0'
    implementation 'org.apache.commons:commons-pool2'
    implementation 'org.zalando:logbook-spring-boot-starter:4.0.1'
    implementation 'com.github.gavlyukovskiy:datasource-proxy-spring-boot-starter:2.0.1'
    implementation 'org.javers:javers-core:7.4.2'
    implementation 'org.mapstruct:mapstruct:1.6.3'
    compileOnly 'org.projectlombok:lombok'
    runtimeOnly 'org.postgresql:postgresql'
    annotationProcessor 'org.projectlombok:lombok'
    annotationProcessor 'org.mapstruct:mapstruct-processor:1.6.3'
    implementation platform('org.instancio:instancio-bom:6.0.0-RC3')
    testImplementation 'org.instancio:instancio-core'
    testImplementation 'org.instancio:instancio-junit'
    testImplementation 'org.testcontainers:testcontainers'
    testImplementation 'org.testcontainers:junit-jupiter:1.21.4'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-liquibase-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-validation-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
    testImplementation 'org.testcontainers:testcontainers-postgresql'
    integrationTestImplementation 'org.testcontainers:testcontainers-postgresql'
    testImplementation 'org.springframework.security:spring-security-test:7.0.5'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testCompileOnly 'org.projectlombok:lombok'
    testAnnotationProcessor 'org.projectlombok:lombok'
}

tasks.register('integrationTest', Test) {
    description = 'Runs integration tests using Testcontainers.'
    group = 'verification'

    testClassesDirs = sourceSets.integrationTest.output.classesDirs
    classpath = sourceSets.integrationTest.runtimeClasspath

    useJUnitPlatform()
    shouldRunAfter test

    maxParallelForks = 1
    forkEvery = 5
    minHeapSize = "512m"
    maxHeapSize = "2048m"
    systemProperty "spring.profiles.active", "test"
}

check.dependsOn integrationTest

tasks.named('test') {
    useJUnitPlatform()
}

tasks.named('processIntegrationTestResources', Copy) {
    duplicatesStrategy = DuplicatesStrategy.INCLUDE
}

tasks.named('sonar') {
    dependsOn jacocoTestReport
}

protobuf {
    protoc {
        artifact = "com.google.protobuf:protoc:4.35.0"
    }
    plugins {
        grpc {
            artifact = "io.grpc:protoc-gen-grpc-java:1.81.0"
        }
    }
    generateProtoTasks {
        all().each { task ->
            task.plugins {
                grpc {}
            }
        }
    }
}
