services:
  user-postgres:
    image: postgres:18-alpine
    container_name: user-postgres
    environment:
      POSTGRES_DB: ${DATABASE_DB}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_SCHEMA: ${DATABASE_SCHEMA}
      APP_DB_USER: ${DOCKER_DB_USER}
      APP_DB_PASSWORD: ${DOCKER_DB_PASSWORD}
    volumes:
        - ./docker-init/init-app-user.sh:/docker-entrypoint-initdb.d/init-app-user.sh
        - pg_data:/var/lib/postgresql
    ports:
      - "5432:5432"

  redis:
    image: redis:7.2-alpine
    container_name: redis
    ports:
      - "6379:6379"

  user-service:
    build: .
    container_name: user-service
    ports:
      - "8080:8080"
    depends_on:
        - user-postgres
        - redis
    env_file:
      - '.env'
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_QUERY_LOGGING_ENABLED: ${DB_QUERY_LOGGING_ENABLED}
      DB_SLOW_QUERY_LOGGING_ENABLED: ${DB_SLOW_QUERY_LOGGING_ENABLED}
      LOG_LEVEL_APP: ${LOG_LEVEL_APP}
      LOG_LEVEL_HIBERNATE: ${LOG_LEVEL_HIBERNATE}
      LOG_LEVEL_LOGBOOK: ${LOG_LEVEL_LOGBOOK}
      APP_AUDIT_ENABLED: ${APP_AUDIT_ENABLED}

volumes:
  pg_data: