services:
  user-postgres:
    image: postgres:${POSTGRES_VERSION}
    container_name: user-postgres
    environment:
      POSTGRES_DB: ${USER_DB_NAME}
      POSTGRES_USER: ${USER_DB_ROOT_USER}
      POSTGRES_PASSWORD: ${USER_DB_ROOT_PASSWORD}
      USER_DB_USER: ${USER_DB_USERNAME}
      USER_DB_PASSWORD: ${USER_DB_PASSWORD}
      USER_DB_SCHEMA: ${USER_DB_SCHEMA}
    volumes:
        - ./docker-init/init-app-user.sh:/docker-entrypoint-initdb.d/init-app-user.sh
        - pg_data:/var/lib/postgresql
    ports:
      - "${USER_POSTGRES_PORT}:5432"
    deploy:
      resources:
        limits:
          memory: 1G
    command: ["postgres","-c", "shared_buffers=256MB","-c", "synchronous_commit=off","-c", "max_connections=50"]

  redis:
    image: redis:${REDIS}
    container_name: redis
    ports:
      - "${REDIS_PORT}:6379"
    deploy:
      resources:
        limits:
          memory: 512M
    command: [ "redis-server", "--maxmemory", "400mb", "--maxmemory-policy", "allkeys-lru" ]

  user-service:
    build: .
    container_name: user-service
    env_file:
      - '.env'
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "${USER_SERVICE_PORT}:${USER_SERVICE_PORT}"
      - "${USER_GRPC_SERVER_PORT}:${USER_GRPC_SERVER_PORT}"
    volumes:
      - ../auth-service/certs:/app/certs:ro
    depends_on:
      - user-postgres
      - redis

networks:
  default:
    name: innowise-network

volumes:
  pg_data: