syntax = "proto3";

package com.minispring.grpc;

option java_multiple_files = true;
option java_package = "com.minispring.grpc.service";
option java_outer_classname = "UserSyncProto";

service AuthGrpcService {
  rpc ChangeStatus (UserStatusRequest) returns (UserStatusResponse);

  rpc DeleteUser (DeleteUserRequest) returns (DeleteUserResponse);
}

message UserStatusRequest {
  string userId = 1;
  bool enabled = 2;
}

message UserStatusResponse {
  bool success = 1;
}

message DeleteUserRequest {
  string userId = 1;
}

message DeleteUserResponse {
  bool success = 1;
}