spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5432/${USER_DB_NAME}?currentSchema=${USER_DB_SCHEMA}
    username: ${USER_DB_USERNAME}
    password: ${USER_DB_PASSWORD}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: localhost
      port: ${REDIS_PORT}
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://localhost:${KC_HTTPS_PORT}/realms/${APP_REALM}/protocol/openid-connect/certs
          issuer-uri: https://localhost:${KC_HTTPS_PORT}/realms/${APP_REALM}
          audience: ${APP_CLIENT_ID}
  grpc:
    client:
      channels:
        auth-service-grpc:
          address: 'localhost:${AUTH_GRPC_SERVER_PORT}'
          negotiation-type: plaintext
    server:
      port: ${USER_GRPC_SERVER_PORT}
      reflection:
        enabled: true

decorator:
  datasource:
    p6spy:
      enable-logging: false
    datasource-proxy:
      logging: slf4j
      multiline: true
      query:
        enable-logging: true
        log-level: info
      slow-query:
        enable-logging: true
        log-level: warn

logging:
  level:
    root: INFO
    com.minispring.userservice: DEBUG
    org.hibernate.SQL: DEBUG
    org.zalando.logbook: TRACE