spring:
  application:
    name: user-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  threads:
    virtual:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        default_schema: ${USER_DB_SCHEMA}
        default_batch_fetch_size: 50
  liquibase:
    enabled: true
    change-log: db/changelog/changelog.yml
    default-schema: ${USER_DB_SCHEMA}
  data:
    web:
      pageable:
        serialization-mode: via_dto
    redis:
      timeout: 2000ms
      lettuce:
        pool:
          enabled: true
          max-active: 32
          max-idle: 16
          min-idle: 8
          max-wait: 1000ms

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  info:
    env:
      enabled: true

logbook:
  format:
    style: json
  strategy: default
  obfuscate:
    parameters:
      - password
      - secret
      - token
      - cvv
      - cardNumber
      - number
  predicate:
    exclude:
      - path: /actuator/**
      - path: /swagger-ui/**
      - path: /v3/api-docs/**

app:
  security:
    card-pepper: ${APP_SECURITY_CARD_SECRET}
    jwt:
      blacklist:
        prefix: ${APP_SECURITY_BLACKLIST_PREFIX}
        ttl: ${APP_SECURITY_TOKEN_LIFESPAN}s
  cache:
    lifecycle:
      default: 1h
      user-info: 24h