#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
        CREATE USER $USER_DB_USER WITH PASSWORD '$USER_DB_PASSWORD';

        GRANT CONNECT, CREATE ON DATABASE $POSTGRES_DB TO $USER_DB_USER;

        CREATE SCHEMA IF NOT EXISTS $USER_DB_SCHEMA;

        GRANT USAGE, CREATE ON SCHEMA $USER_DB_SCHEMA TO $USER_DB_USER;

        ALTER USER $USER_DB_USER SET search_path TO $USER_DB_SCHEMA;

        ALTER DEFAULT PRIVILEGES IN SCHEMA $USER_DB_SCHEMA GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON TABLES TO $USER_DB_USER;

        ALTER DEFAULT PRIVILEGES IN SCHEMA $USER_DB_SCHEMA GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO $USER_DB_USER;
EOSQL