#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER $APP_DB_USER WITH PASSWORD '$APP_DB_PASSWORD';

    GRANT CONNECT, CREATE ON DATABASE $POSTGRES_DB TO $APP_DB_USER;

    CREATE SCHEMA IF NOT EXISTS $POSTGRES_SCHEMA;

    GRANT USAGE, CREATE ON SCHEMA $POSTGRES_SCHEMA TO $APP_DB_USER;

    ALTER DEFAULT PRIVILEGES IN SCHEMA $POSTGRES_SCHEMA GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON TABLES TO $APP_DB_USER;

    ALTER DEFAULT PRIVILEGES IN SCHEMA $POSTGRES_SCHEMA GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO $APP_DB_USER;
EOSQL