spring:
  application:
    name: user-service-test

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: public
    open-in-view: false

  security:
    oauth2:
      client:
        registration:
          user-service-internal:
            provider: keycloak
            client-id: "account"
            authorization-grant-type: client_credentials
        provider:
          keycloak:
            token-uri: "http://localhost:9999/dummy"
      resourceserver:
        jwt:
          jwk-set-uri: "http://localhost:9999/dummy"
          issuer-uri: "http://localhost:9999/dummy"
          audience: "account"

  liquibase:
    enabled: true
    change-log: db/changelog/changelog.yml
    default-schema: public

  data:
    redis:
      timeout: 1000ms
      lettuce:
        pool:
          enabled: true
          max-active: 8
          max-idle: 4
          min-idle: 2
          max-wait: 500ms

app:
  security:
    card-pepper: secret_test
    jwt:
      blacklist:
        prefix: banned_users
        ttl: 300s
  cache:
    lifecycle:
      default: 1h
      user-info: 24h